"""Summarize train/validation/test predictions generated by the training core."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

from src.dataset import repository_root


def summarize(path: Path) -> list[dict]:
    frame = pd.read_csv(path)
    required = {"true", "pred", "split", "unit"}
    if not required.issubset(frame.columns):
        raise ValueError(f"Missing result columns in {path}: {sorted(required - set(frame.columns))}")
    if set(frame["unit"]) != {"eV"}:
        raise ValueError(f"Expected eV predictions in {path}")
    output = []
    for split, subset in frame.groupby("split"):
        truth = subset["true"].to_numpy(dtype=float)
        prediction = subset["pred"].to_numpy(dtype=float)
        error = prediction - truth
        total = np.sum((truth - truth.mean()) ** 2)
        r2 = float(1 - np.sum(error ** 2) / total) if len(truth) > 1 and total > 0 else float("nan")
        output.append({"source": path.as_posix(), "split": split,
                       "count": len(subset), "unit": "eV", "r2": r2,
                       "mae": float(np.mean(np.abs(error))),
                       "rmse": float(np.sqrt(np.mean(error ** 2)))})
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-dir", type=Path, default=repository_root() / "results")
    parser.add_argument("--output", type=Path, default=repository_root() / "results/metrics_summary.csv")
    args = parser.parse_args()
    paths = sorted(args.results_dir.glob("*/seed_*/mode_*/results.csv"))
    if not paths:
        parser.error(f"No training results.csv files found under {args.results_dir}")
    rows = [row for path in paths for row in summarize(path)]
    args.output.parent.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(rows).to_csv(args.output, index=False)
    print(f"Wrote {len(rows)} metric rows to {args.output}")


if __name__ == "__main__":
    main()
